# .github/workflows/main.yml

name: ğŸš€ Deploy auto-run_app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying ğŸš€ Auto-deploy app
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy please')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: github-actions@gcloudautodeploy.iam.gserviceaccount.com
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Building (ğŸ—)
        run: |-
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_ID }}
            
        #run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_ID }}:${{ GITHUB_SHA }}

      # Setup gcloud CLI
      - name: Deploy (ğŸš€)
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.GCP_APP_ID }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_ID }}
          region: southamerica-east1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

